Criação de Louvores e Temas
ibcalvario/ibcalvario.github.io pull request #2
Opened 2021-09-01 15:11 UTC by MarceloCFSF

* Adicionei a parte sobre criação de louvores usando o Pro Presenter
* Coloquei um tema para melhorar o visual da Documentação. O tema é o Midnight porém pode ser facilmente alterado no arquivo [_config.yml](_config.yml).
* Coloquei um botão para retornar para a página anterior em [Criação de louvor no propresenter](criacao-de-louvor-no-propresenter/index.md). Futuramente pretendo colocar em todas as páginas, porém sem ser necessário colocar em cada uma individualmente

2021-09-12 12:08 UTC, denisnietto requested changes
Renomeia os arquivo de imagem que tem os caracteres especiais.
Tem alguns com sinal de +.
O melhor é ser nomes sempre simples, letras, números.
Hífen ou underlines no máximo.

Talvez hoje isso não seja mais um problema, mas acho melhor previnir.

2021-09-12 12:08 UTC, denisnietto commented on 404.html
> +  <h1>404</h1>
Vamos fazer uma página de 404 bem objetiva e clara.
Sugiro a gente remover esse título e deixar tudo em português.

2021-09-12 12:08 UTC, denisnietto commented on Gemfile
> +source "https://rubygems.org"
Vamos criar uma página somente para indicar o que tem q ser feito pra rodar local.
Sugiro criar um item na https://ibcalvario.github.io/sobre-a-documentacao/
Algo simples como isso, porém em português: https://gist.github.com/akshaymohite/e33f90217c3ca0ffa70abd840a8574de

2021-09-12 12:08 UTC, denisnietto commented on _config.yml
> +# Welcome to Jekyll!
Remove esses comentários padrões da 1 até a 19 e da 39 até a 57

2021-09-12 13:28 UTC, denisnietto requested changes

2021-09-12 13:28 UTC, denisnietto commented on ibcalvariotv/transmissao/criacao-de-louvor-no-propresenter/index.md
> +<!-- Colocar imagem de exemplo do chroma key -->
Aqui você está apresentando novamente o ProPresenter, mas ele já foi apresentado em outra parte da documentação.
Faz referencia a esse link: https://ibcalvario.github.io/ibcalvariotv/transmissao/equipamentos-e-programas/#propresenter

2021-09-12 13:28 UTC, denisnietto commented on ibcalvariotv/transmissao/criacao-de-louvor-no-propresenter/index.md
> +</div>
Na visualização isso ficou estranho, mesmo no Word já estava.
Além disso vamos evitar usar HTML dentro do mark down, só quando necessário mesmo, não me parece que esse é um caso.

2021-09-12 13:28 UTC, denisnietto commented on ibcalvariotv/transmissao/criacao-de-louvor-no-propresenter/index.md
> +</div>
Idem ao anterior.

2021-09-13 23:50 UTC, MarceloCFSF commented on ibcalvariotv/transmissao/criacao-de-louvor-no-propresenter/index.md
> +</div>
Eu fiz isso pra colocar as imagens em 2 colunas. Não consegui achar como fazer isso usando Markdown. 
Só não entendi a primeira parte, como assim no "Word" e está falando da visualização do código ou na web?

2021-09-16 20:18 UTC, MarceloCFSF commented
Atualizações pedidas feitas

2021-09-18 11:21 UTC, denisnietto approved these changes

2021-09-18 11:21 UTC, denisnietto commented on ibcalvariotv/transmissao/equipamentos-e-programas/propresenter/index.md
> +Ele é gratuito, porém sem algumas funcionalidades, além de conter uma marca d'agua ao apresentar algo.
Acho que já tinha lido sobre a única mudança ser a marca dagua. Você sabe de outras?
Na verdade ele não é gratuíto, é que o uso de forma gratuíta tem essa limitação, posso aprovar assim e depois eu mudo.
Mas foi bom mesmo lembrar de escrever sobre isso.

2021-09-18 11:21 UTC, merged